"""Excel/CSV processing — wraps tools/process_sheet.py for server use."""
from __future__ import annotations
import importlib.util
import json
import re
import sys
from pathlib import Path
from typing import Any

from . import config

_SHEET_MODULE = None


def _load_sheet_module():
    """Import tools/process_sheet.py without requiring it to be a package."""
    global _SHEET_MODULE
    if _SHEET_MODULE is not None:
        return _SHEET_MODULE
    sheet_py = config.ROOT / "tools" / "process_sheet.py"
    spec = importlib.util.spec_from_file_location("atlas_process_sheet", sheet_py)
    if not spec or not spec.loader:
        raise RuntimeError(f"Could not load {sheet_py}")
    mod = importlib.util.module_from_spec(spec)
    sys.modules["atlas_process_sheet"] = mod
    spec.loader.exec_module(mod)
    _SHEET_MODULE = mod
    return mod


def process_file(path: Path, previous: list[dict] | None = None) -> list[dict]:
    """Read an .xlsx, .xls, or .csv file and return community records."""
    mod = _load_sheet_module()
    ext = path.suffix.lower()
    if ext in (".xlsx", ".xls"):
        rows, _ = mod.load_xlsx_rows(path, None)
    elif ext == ".csv":
        rows, _ = mod.load_csv_rows(path)
    else:
        raise ValueError(f"Unsupported file type: {ext}")
    records = mod.process_rows(rows, previous, verbose=False)
    return records


def write_communities_js(records: list[dict]) -> None:
    """Write `communities-data.js` so static dashboard reads fresh data."""
    payload = json.dumps(records, ensure_ascii=False, indent=2)
    config.COMMUNITIES_JS.write_text(
        "// Auto-generated by server.processor — do not edit by hand.\n"
        f"window.COMMUNITIES = {payload};\n",
        encoding="utf-8",
    )


# --- enrichment so the API surfaces the same shape the dashboard expects --- #

_NA_VALUES = {"missing information", "needs review", "duplicate record",
              "no definite value", "n/a", "na", "-", ""}


def _is_na(value: Any) -> bool:
    """A field counts as N/A only if it's truly empty or one of the known
    placeholder phrases. Even a single character like 'b' or 'v' (often used
    as WIP scratch values) should count as filled — otherwise the team's
    test data silently disappears from the dashboard."""
    if value is None:
        return True
    s = str(value).strip().lower()
    return s in _NA_VALUES


def _slugify(s: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", str(s or "").lower())
    return re.sub(r"^-|-$", "", s)[:60]


def _parse_pop(v: Any) -> int | None:
    if v is None:
        return None
    m = re.search(r"\d+", str(v).replace(",", ""))
    return int(m.group(0)) if m else None


def enrich(records: list[dict]) -> list[dict]:
    """Add `id`, `hasXxx`, `population` (numeric) fields used by the UI."""
    out = []
    for r in records:
        c = dict(r)
        c["id"] = _slugify(r.get("name") or "")
        c["hasPhysical"] = not _is_na(r.get("physical"))
        c["hasMental"] = not _is_na(r.get("mental"))
        c["hasSpiritual"] = not _is_na(r.get("spiritual"))
        c["hasEmotional"] = not _is_na(r.get("emotional"))
        c["hasYouth"] = not _is_na(r.get("youth"))
        c["hasSurvivors"] = not _is_na(r.get("survivors"))
        c["hasConnect"] = not _is_na(r.get("connect"))
        pop = _parse_pop(r.get("population"))
        if pop is not None:
            c["populationNumeric"] = pop
        out.append(c)
    return out


def load_initial_records() -> list[dict]:
    """Read communities-data.js shipped with the repo to seed the DB on first boot."""
    if not config.COMMUNITIES_JS.exists():
        return []
    text = config.COMMUNITIES_JS.read_text(encoding="utf-8")
    m = re.search(r"window\.COMMUNITIES\s*=\s*(\[.*\])\s*;?\s*$", text, re.S)
    if not m:
        return []
    try:
        return json.loads(m.group(1))
    except json.JSONDecodeError:
        return []
